#region 2.2 List all model elements:

      UIApplication app = commandData.Application;
      Document doc = app.ActiveUIDocument.Document;

      FilteredElementCollector collector
        = new FilteredElementCollector( doc )
          .WhereElementIsNotElementType();

      List<string> a = new List<string>();

      // we could use a LINQ query here instead:

      foreach( Element e in collector )
      {
        //  && null != e.Materials
        //  && 0 < e.Materials.Size

        if( null != e.Category
          && e.Category.HasMaterialQuantities )
        {
          a.Add( string.Format(
            "Category={0}; Name={1}; Id={2}",
            e.Category.Name, e.Name,
            e.Id.IntegerValue ) );
        }
      }

      LabUtils.InfoMsg(
        "Project contains {0} model element{1}{2}", a );

      return Result.Failed;

      #endregion // 2.2 List all model elements