#region Get Model Extents
    /// <summary>
    /// Return a bounding box enclosing all model 
    /// elements using only quick filters.
    /// </summary>
    BoundingBoxXYZ GetModelExtents( Document doc )
    {
      FilteredElementCollector quick_model_elements
        = new FilteredElementCollector( doc )
          .WhereElementIsNotElementType()
          .WhereElementIsViewIndependent();

      IEnumerable<BoundingBoxXYZ> boxes = quick_model_elements
        .Where<Element>( e => null != e.Category )
        .Select<Element, BoundingBoxXYZ>( e
           => e.get_BoundingBox( null ) );

      return boxes.Aggregate<BoundingBoxXYZ>( ( a, b )
        => { a.ExpandToContain( b ); return a; } );
    }
    #endregion // Get Model Extents